# Generated by Django 2.1.3 on 2018-11-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FLights',
            new_name='Flight',
        ),
    ]
